PeopleTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.tableNamePeople}
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST
